# Generated by Django 3.2 on 2023-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('task_name', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Uncompleted', 'Uncompleted')], default='Uncompleted', max_length=100)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todo',
                'ordering': ('-created_at',),
            },
        ),
    ]
